# Bun configuration
[install]
# Use Bun's lockfile format
lockfile = true
# Enable peer dependencies
peer = true

[run]
# Use Bun's runtime for scripts
bun = true

[build]
# Optimize for production
minify = true
